export const coffeeCards = [
  {
    title: "Aromistico Coffee 1 kg",
    img: "img/best_img/aromistico.jpg",
		descr: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Error ipsum consequuntur esse. Velit ex quaerat tempora est qui facilis atque quis",
    country: "Brazil",
    price: 6.99,
    id: 1,
  },
  {
    title: "Comfoods Coffee 1 kg",
    img: "img/best_img/presto.jpg",
		descr: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Error ipsum consequuntur esse. Velit ex quaerat tempora est qui facilis atque quis",
    country: "Kenya",
    price: 7.1,
    id: 2,
  },
  {
    title: "Tchibo Coffee 1 kg",
    img: "/img/aromico.jpg",
		descr: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Error ipsum consequuntur esse. Velit ex quaerat tempora est qui facilis atque quis",
    country: "Columbia",
    price: 8,
    id: 3,
  },
  {
    title: "Vinacafe Coffee 1 kg",
    img: "/img/aromico.jpg",
		descr: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Error ipsum consequuntur esse. Velit ex quaerat tempora est qui facilis atque quis",
    country: "Columbia",
    price: 8,
    id: 4,
  },
  {
    title: "Paulig Coffee 1 kg",
    img: "img/best_img/aromistico.jpg",
		descr: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Error ipsum consequuntur esse. Velit ex quaerat tempora est qui facilis atque quis",
    country: "Brazil",
    price: 6.99,
    id: 5,
  },
  {
    title: "Franck Coffee 1 kg",
    img: "img/best_img/aromistico.jpg",
		descr: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Error ipsum consequuntur esse. Velit ex quaerat tempora est qui facilis atque quis",
    country: "Brazil",
    price: 6.99,
    id: 6,
  },
];
